Fix delete command duplicate index
AY2223S2-CS2103T-W12-2/tp pull request #266
Opened 2023-04-07 11:53 UTC by Bentimate

Fixed bug where delete command does not clear after duplicate index. 
Now duplicate indexes are disallowed and an error is thrown.

2023-04-07 12:16 UTC, EvitanRelta requested changes

2023-04-07 12:16 UTC, EvitanRelta commented on src/main/java/seedu/address/commons/core/Messages.java
> +    public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The person index provided is invalid!";
Remove the `!`, as we're not allowed to "enhance" the error message.

But adding `MESSAGE_DUPLICATE_PERSONS_INDEX` should be fine, since its a bug.

2023-04-07 13:00 UTC, Bentimate commented
fixed proposed changes

2023-04-07 14:23 UTC, EvitanRelta commented
also rmb to label thr PR with the Bug label

2023-04-07 14:59 UTC, Bentimate commented
With the most recent change, i have made it such that:
`delete 1 1` gives a new error message
`delete` shows the command usage
`delete 1a` shows invalid index
This is done so that delete command is consistent with all other commands.

Please be careful and help to confirm this, i have no idea if this is allowed in 1.4

2023-04-08 09:39 UTC, EvitanRelta approved these changes
@Bentimate I made some changes:
- Refactored the error throwing, so that it doesn't throw -> catch -> throw
- Removed the "One or more index values are not positive integers." error message, since it wasn't actually used in v1.3 _(it was only thrown then caught and replaced with the invalid format msg)_
- Added more tests

2023-04-08 12:07 UTC, merged